import { NextRequest, NextResponse } from "next/server";
import prisma from "@/db/prisma";
import { getServerSession } from "next-auth";
import { authOptions } from "@/app/api/auth/[...nextauth]/option";
import jsPDF from "jspdf";

export async function GET(
  request: NextRequest,
  context: { params: Promise<{ aggrementId: string }> },
) {
  try {
    const session = await getServerSession(authOptions);
    if (!session || session.user.role !== "admin") {
      return NextResponse.json({ error: "Unauthorized" }, { status: 401 });
    }

    const { aggrementId } = await context.params;

    const agreement = await prisma.liaisonAgreement.findUnique({
      where: { id: aggrementId },
      include: { application: true },
    });

    if (!agreement) {
      return NextResponse.json({ error: "Agreement not found" }, { status: 404 });
    }

    const doc = new jsPDF();
    let y = 20;
    const nextLine = (gap = 7) => { y += gap; };
    const checkPage = () => { if (y > 250) { doc.addPage(); y = 20; } };

    const termStart = agreement.agreement_start_date
      ? new Date(agreement.agreement_start_date).toLocaleDateString()
      : "N/A";
    const termEnd = agreement.agreement_end_date
      ? new Date(agreement.agreement_end_date).toLocaleDateString()
      : "Indefinite";

    // Header
    doc.setFontSize(18);
    doc.setFont("helvetica", "bold");
    doc.text(agreement.agreement_title || "Speedyo Dealership Partnership Liaison Agreement", 20, y);
    nextLine(12);

    // Position
    doc.setFontSize(12);
    doc.setFont("helvetica", "bold");
    doc.text("Position Title", 20, y); nextLine(7);
    doc.setFont("helvetica", "normal");
    doc.setFontSize(10);
    doc.text(agreement.position_title || "Liaison Agent", 20, y); nextLine(10);

    // Compensation
    checkPage();
    doc.setFontSize(12);
    doc.setFont("helvetica", "bold");
    doc.text("Compensation", 20, y); nextLine(7);
    doc.setFont("helvetica", "normal");
    doc.setFontSize(10);
    doc.text(`Fixed Fee: ${agreement.fixed_fee_percentage ?? "10"}% of service fee per assisted sale`, 20, y); nextLine();
    doc.text(`Residual Pay: ${agreement.residual_pay_percentage ?? "3"}% for subsequent sales from referred dealerships`, 20, y); nextLine();
    doc.text("Payment upon successful vehicle sale", 20, y); nextLine(10);

    // Term
    checkPage();
    doc.setFontSize(12);
    doc.setFont("helvetica", "bold");
    doc.text("Term", 20, y); nextLine(7);
    doc.setFont("helvetica", "normal");
    doc.setFontSize(10);
    doc.text(`Effective from ${termStart} to ${termEnd}`, 20, y); nextLine();
    doc.text(`${agreement.termination_notice_days ?? 30} days notice required for termination`, 20, y); nextLine(10);

    // Application Info
    if (agreement.application) {
      const app = agreement.application;
      checkPage();
      doc.setFontSize(12);
      doc.setFont("helvetica", "bold");
      doc.text("Application Information", 20, y); nextLine(7);
      doc.setFont("helvetica", "normal");
      doc.setFontSize(10);
      doc.text(`Name: ${app.full_name}`, 20, y); nextLine();
      doc.text(`Email: ${app.email}`, 20, y); nextLine();
      doc.text(`Phone: ${app.phone}`, 20, y); nextLine();
      doc.text(`Language Proficiency: ${app.language_proficiency.replaceAll("_", " ")}`, 20, y); nextLine();
      if (app.address) { doc.text(`Address: ${app.address}`, 20, y); nextLine(); }
      if (app.previous_experience) { checkPage(); doc.text(`Previous Experience: ${app.previous_experience}`, 20, y); nextLine(); }
      if (app.automotive_knowledge) { checkPage(); doc.text(`Automotive Knowledge: ${app.automotive_knowledge}`, 20, y); nextLine(); }
      if (app.availability) { doc.text(`Availability: ${app.availability}`, 20, y); nextLine(); }
    }

    // Footer
    doc.setFontSize(8);
    doc.setTextColor(128);
    doc.text(`Agreement ID: ${agreement.id} | Generated by Speedyo`, 20, 285);

    const pdfBuffer = Buffer.from(doc.output("arraybuffer"));
    const filename = `Liaison_Agreement_${agreement.id}.pdf`;

    return new NextResponse(pdfBuffer, {
      status: 200,
      headers: {
        "Content-Type": "application/pdf",
        "Content-Disposition": `attachment; filename="${filename}"`,
      },
    });
  } catch (error) {
    console.error("Failed to generate liaison PDF", error);
    return NextResponse.json({ error: "Internal server error" }, { status: 500 });
  }
}