import { NextRequest, NextResponse } from "next/server";
import prisma from "@/db/prisma";

export async function GET(_req: NextRequest, ctx: { params: Promise<{ vehicleId: string }> }) {
  try {
    const { vehicleId } = await ctx.params;
    if (!vehicleId) return NextResponse.json({ error: "Missing vehicleId" }, { status: 400 });

    const msr = await prisma.managedSaleRequest.findFirst({
      where: { created_vehicle_id: vehicleId },
      orderBy: { createdAt: "desc" },
      select: {
        id: true,
        createdAt: true,
        updatedAt: true,
        created_vehicle_id: true,
        service_fee_amount: true,
        owner_receives_amount: true,
        final_sale_price_for_buyer: true,
        financing_available: true,
        warranty_available: true,
        warranty_link: true,
        drive_type: true,
        engine_size: true,
        body_type: true,
        exterior_color: true,
        interior_color: true,
        doors: true,
        seating_capacity: true,
        steering_wheel: true,
        engine_type: true,
        power_output: true,
        fuel_efficiency: true,
        drivetrain: true,
        power_sliding_doors: true,
        headlights: true,
        fog_lights: true,
        alloy_wheels: true,
        spoiler: true,
        tinted_windows: true,
        roof_type: true,
        side_mirrors: true,
        body_condition: true,
        air_conditioning: true,
        upholstery: true,
        seat_type: true,
        seat_adjustments: true,
        navigation_system: true,
        rear_camera: true,
        parking_sensors: true,
        power_windows: true,
        interior_lighting: true,
        cup_holders_storage: true,
        child_lock_isofix: true,
        display_screen_size: true,
        rear_entertainment_system: true,
        digital_dashboard_display: true,
        infotainment_system: true,
        steering_wheel_controls: true,
        airbags: true,
        bluetooth: true,
        usb_ports: true,
        twelve_v_outlet: true,
        smart_key_push_start: true,
        keyless_entry: true,
        remote_door_locking: true,
        voice_command_hands_free: true,
        abs: true,
        esc_stability_control: true,
        lane_departure_warning: true,
        collision_mitigation: true,
        cruise_control: true,
        traction_control: true,
        hill_start_assist: true,
        immobilizer_alarm: true,
        seat_belt_sensors: true,
      },
    });

    if (!msr) return NextResponse.json({ success: true, msr: null }, { status: 200 });

    const vehicle_details = {
      financing_available: msr.financing_available ?? null,
      warranty_available: msr.warranty_available ?? null,
      warranty_link: msr.warranty_link ?? null,
      drive_type: msr.drive_type ?? null,
      engine_size: msr.engine_size ?? null,
      body_type: msr.body_type ?? null,
      exterior_color: msr.exterior_color ?? null,
      interior_color: msr.interior_color ?? null,
      doors: msr.doors ?? null,
      seating_capacity: msr.seating_capacity ?? null,
      steering_wheel: msr.steering_wheel ?? null,
      engine_type: msr.engine_type ?? null,
      power_output: msr.power_output ?? null,
      fuel_efficiency: msr.fuel_efficiency ?? null,
      drivetrain: msr.drivetrain ?? null,

      power_sliding_doors: msr.power_sliding_doors ?? null,
      headlights: msr.headlights ?? null,
      fog_lights: msr.fog_lights ?? null,
      alloy_wheels: msr.alloy_wheels ?? null,
      spoiler: msr.spoiler ?? null,
      tinted_windows: msr.tinted_windows ?? null,
      roof_type: msr.roof_type ?? null,
      side_mirrors: msr.side_mirrors ?? null,

      body_condition: msr.body_condition ?? null,
      air_conditioning: msr.air_conditioning ?? null,
      upholstery: msr.upholstery ?? null,
      seat_type: msr.seat_type ?? null,
      seat_adjustments: msr.seat_adjustments ?? null,
      navigation_system: msr.navigation_system ?? null,
      rear_camera: msr.rear_camera ?? null,
      parking_sensors: msr.parking_sensors ?? null,
      power_windows: msr.power_windows ?? null,
      interior_lighting: msr.interior_lighting ?? null,
      cup_holders_storage: msr.cup_holders_storage ?? null,
      child_lock_isofix: msr.child_lock_isofix ?? null,
      display_screen_size: msr.display_screen_size ?? null,
      rear_entertainment_system: msr.rear_entertainment_system ?? null,
      digital_dashboard_display: msr.digital_dashboard_display ?? null,
      infotainment_system: msr.infotainment_system ?? [],
      steering_wheel_controls: msr.steering_wheel_controls ?? [],
      airbags: msr.airbags ?? [],
      bluetooth: msr.bluetooth ?? null,
      usb_ports: msr.usb_ports ?? null,
      twelve_v_outlet: msr.twelve_v_outlet ?? null,
      smart_key_push_start: msr.smart_key_push_start ?? null,
      keyless_entry: msr.keyless_entry ?? null,
      remote_door_locking: msr.remote_door_locking ?? null,
      voice_command_hands_free: msr.voice_command_hands_free ?? null,
      abs: msr.abs ?? null,
      esc_stability_control: msr.esc_stability_control ?? null,
      lane_departure_warning: msr.lane_departure_warning ?? null,
      collision_mitigation: msr.collision_mitigation ?? null,
      cruise_control: msr.cruise_control ?? null,
      traction_control: msr.traction_control ?? null,
      hill_start_assist: msr.hill_start_assist ?? null,
      immobilizer_alarm: msr.immobilizer_alarm ?? null,
      seat_belt_sensors: msr.seat_belt_sensors ?? null,
    };

    return NextResponse.json(
      {
        success: true,
        msr: {
          id: msr.id,
          createdAt: msr.createdAt,
          updatedAt: msr.updatedAt,
          created_vehicle_id: msr.created_vehicle_id,
          service_fee_amount: msr.service_fee_amount,
          owner_receives_amount: msr.owner_receives_amount,
          final_sale_price_for_buyer: msr.final_sale_price_for_buyer,
          vehicle_details,
        },
      },
      { status: 200 },
    );
  } catch (error) {
    console.error("GET /api/managed-sale-requests/by-vehicle/[vehicleId] failed:", error);
    return NextResponse.json({ error: "Internal server error" }, { status: 500 });
  }
}

