import { NextRequest, NextResponse } from "next/server";
import prisma from "@/db/prisma";
import { getServerSession } from "next-auth";
import { authOptions } from "@/app/api/auth/[...nextauth]/option";
import jsPDF from "jspdf";

export async function GET(
  request: NextRequest,
  context: { params: Promise<{ aggrementId: string }> },
) {
  try {
    const session = await getServerSession(authOptions);
    if (!session || session.user.role !== "admin") {
      return NextResponse.json({ error: "Unauthorized" }, { status: 401 });
    }

    const { aggrementId } = await context.params;

    const agreement = await prisma.dealershipVehicleAgreement.findUnique({
      where: { id: aggrementId },
    });

    if (!agreement) {
      return NextResponse.json({ error: "Agreement not found" }, { status: 404 });
    }

    // ── Generate PDF ──────────────────────────────────────────────
    const doc = new jsPDF();
    let y = 20;

    const nextLine = (gap = 7) => { y += gap; };
    const checkPage = () => {
      if (y > 250) { doc.addPage(); y = 20; }
    };

    // ── Header ────────────────────────────────────────────────────
    doc.setFontSize(20);
    doc.setFont("helvetica", "bold");
    doc.text("Speedio Managed Sales Service", 20, y);
    nextLine(10);
    doc.setFontSize(16);
    doc.text("Dealership Vehicle Agreement", 20, y);
    nextLine(15);

    // ── Dealership Info ───────────────────────────────────────────
    doc.setFontSize(12);
    doc.setFont("helvetica", "bold");
    doc.text("Dealership Information", 20, y);
    nextLine(8);
    doc.setFontSize(10);
    doc.setFont("helvetica", "normal");

    doc.text(`Dealership Name: ${agreement.dealership_name}`, 20, y); nextLine();
    doc.text(`Representative: ${agreement.representative_name}`, 20, y); nextLine();
    doc.text(`Email: ${agreement.email}`, 20, y); nextLine();
    if (agreement.phone) { doc.text(`Phone: ${agreement.phone}`, 20, y); nextLine(); }
    if (agreement.address) { doc.text(`Address: ${agreement.address}`, 20, y); nextLine(); }
    if (agreement.license_number) { doc.text(`License Number: ${agreement.license_number}`, 20, y); nextLine(); }
    nextLine(5);

    // ── Agreement Details ─────────────────────────────────────────
    checkPage();
    doc.setFontSize(12);
    doc.setFont("helvetica", "bold");
    doc.text("Agreement Details", 20, y);
    nextLine(8);
    doc.setFontSize(10);
    doc.setFont("helvetica", "normal");

    doc.text(`Service Fee: ${agreement.service_fee_amount ? `¥${Number(agreement.service_fee_amount).toLocaleString()}` : "Varies per vehicle"}`, 20, y); nextLine();
    doc.text(`Status: ${agreement.status.replace("_", " ").toUpperCase()}`, 20, y); nextLine();
    doc.text(`Created: ${agreement.createdAt ? new Date(agreement.createdAt).toLocaleDateString() : "N/A"}`, 20, y); nextLine();
    if (agreement.signed_at) {
      doc.text(`Signed: ${new Date(agreement.signed_at).toLocaleDateString()}`, 20, y); nextLine();
    }
    if (agreement.signed_by_name) {
      doc.text(`Signed By: ${agreement.signed_by_name}`, 20, y); nextLine();
    }
    nextLine(5);

    // ── Admin Notes ───────────────────────────────────────────────
    if (agreement.admin_notes) {
      checkPage();
      doc.setFontSize(12);
      doc.setFont("helvetica", "bold");
      doc.text("Admin Notes", 20, y);
      nextLine(8);
      doc.setFontSize(10);
      doc.setFont("helvetica", "normal");
      doc.text(agreement.admin_notes, 20, y);
      nextLine(10);
    }

    // ── Footer ────────────────────────────────────────────────────
    doc.setFontSize(8);
    doc.setTextColor(128);
    doc.text(`Agreement ID: ${agreement.id} | Generated by Speedyo`, 20, 285);

    // ── Output ────────────────────────────────────────────────────
    const pdfBuffer = Buffer.from(doc.output("arraybuffer"));
    const filename = `Agreement_${agreement.dealership_name.replace(/\s+/g, "_")}_Managed_Sales.pdf`;

    return new NextResponse(pdfBuffer, {
      status: 200,
      headers: {
        "Content-Type": "application/pdf",
        "Content-Disposition": `attachment; filename="${filename}"`,
      },
    });
  } catch (error) {
    console.error("Failed to generate PDF", error);
    return NextResponse.json({ error: "Internal server error" }, { status: 500 });
  }
}